# Generated by Django 5.1.7 on 2025-03-24 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idpaciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('telefono', models.PositiveIntegerField(verbose_name='Telefono')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('idconsulta', models.AutoField(primary_key=True, serialize=False)),
                ('fechaconsulta', models.DateField(auto_now=True, verbose_name='Fecha de consulta')),
                ('horaconsulta', models.TimeField(auto_now=True, verbose_name='Hora consulta')),
                ('precioconsulta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Altura')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Temperatura')),
                ('signosvitales', models.CharField(max_length=500, verbose_name='Signos vitales')),
                ('diagnostico', models.CharField(max_length=500, verbose_name='Diagnostico')),
                ('tratamiento', models.CharField(max_length=500, verbose_name='Tratamiento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('idcita', models.AutoField(primary_key=True, serialize=False)),
                ('fechacita', models.DateField(verbose_name='Fecha de cita')),
                ('horacita', models.CharField(choices=[('8', '8:00 - 9:00'), ('9', '9:00 - 10:00'), ('10', '10:00 - 11:00'), ('11', '11:00 - 12:00'), ('13', '01:00 - 02:00'), ('14', '02:00 - 03:00'), ('15', '03:00 - 04:00'), ('16', '04:00 - 05:00'), ('17', '05:00 - 06:00')], max_length=11, verbose_name='Hora cita')),
                ('observaciones', models.CharField(max_length=500, verbose_name='Observaciones')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.paciente')),
            ],
        ),
    ]
