# Generated by Django 4.2.20 on 2025-03-25 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='precioconsulta',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='signosvitales',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='temperatura',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='tratamiento',
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('idreceta', models.AutoField(primary_key=True, serialize=False)),
                ('medicamento', models.CharField(max_length=500, verbose_name='Medicamento')),
                ('dosis', models.CharField(max_length=500, verbose_name='Dosis')),
                ('duracion', models.CharField(max_length=500, verbose_name='Duracion')),
                ('indicaciones', models.CharField(max_length=500, verbose_name='Indicaciones')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.consulta')),
            ],
        ),
    ]
