# Generated by Django 4.2.20 on 2025-03-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_remove_consulta_altura_remove_consulta_peso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='altura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Altura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Peso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='precioconsulta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='presionarterial',
            field=models.CharField(default=0, max_length=7, verbose_name='Presion arterial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='temperatura',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Temperatura'),
            preserve_default=False,
        ),
    ]
