# Generated by Django 4.2.20 on 2025-03-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_consulta_altura_consulta_peso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='fechareceta',
            field=models.DateField(auto_now=True, verbose_name='Fecha de receta'),
        ),
    ]
