# Generated by Django 5.1.4 on 2024-12-11 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idpaciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.IntegerField()),
                ('sexo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=150)),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('idcita', models.AutoField(primary_key=True, serialize=False)),
                ('fechacita', models.DateField()),
                ('horacita', models.TimeField()),
                ('preciocita', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('diagnostico', models.CharField(max_length=200)),
                ('observaciones', models.CharField(max_length=500)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('idreceta', models.AutoField(primary_key=True, serialize=False)),
                ('fechareceta', models.DateField()),
                ('medicamentos', models.CharField(max_length=200)),
                ('tratamiento', models.CharField(max_length=300)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.cita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.paciente')),
            ],
        ),
    ]
