# Generated by Django 5.1.4 on 2024-12-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_alter_paciente_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fechacita',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
