# Generated by Django 5.1.4 on 2024-12-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0006_alter_cita_fechacita_alter_paciente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='horacita',
            field=models.TimeField(auto_now=True),
        ),
    ]
