# Generated by Django 5.1.4 on 2024-12-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0008_cita_peso_cita_presionarterial_cita_temperatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='cita',
        ),
        migrations.AlterField(
            model_name='receta',
            name='fechareceta',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_creacion',
            field=models.DateField(auto_now=True),
        ),
    ]
