# Generated by Django 4.2.17 on 2024-12-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0009_remove_receta_cita_alter_receta_fechareceta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='F', max_length=1, null=True),
        ),
    ]
